\connect MyWebApi.Dev
 
-- Table: public.Feedbacks

-- DROP TABLE public."Feedbacks";

CREATE TABLE IF NOT EXISTS public."Feedbacks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Content" text COLLATE pg_catalog."default",
    "IsPublic" boolean NOT NULL,
    "IsPublishable" boolean NOT NULL,
    "IsAnonymous" boolean NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "UserName" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Feedbacks"
    OWNER to admin;

INSERT INTO public."Feedbacks"(
	"Id", "Content", "IsPublic", "IsPublishable", "IsAnonymous", "Date", "UserName")
	VALUES (1, 'Feedback 1', true, true, false, '2021-12-06 20:27:28.916', 'Default User');

INSERT INTO public."Feedbacks"(
	"Id", "Content", "IsPublic", "IsPublishable", "IsAnonymous", "Date", "UserName")
	VALUES (2, 'Feeback 2', false, true, true, '2021-12-06 20:27:28.916', 'Default User');
