// <auto-generated />
using System;
using Hospital.SharedModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hospital.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20211118011837_AddedPatientMedicalInfo")]
    partial class AddedPatientMedicalInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Hospital.GraphicalEditor.Model.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Hospital.GraphicalEditor.Model.Building", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Areaid")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<int>("MapPositionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Areaid");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Info = "Gynecology",
                            MapPositionId = 1,
                            Name = "Hospital I"
                        },
                        new
                        {
                            id = 2,
                            Info = "",
                            MapPositionId = 2,
                            Name = "Hospital II"
                        });
                });

            modelBuilder.Entity("Hospital.GraphicalEditor.Model.Floor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            BuildingId = 1,
                            Level = "Ground floor"
                        },
                        new
                        {
                            id = 2,
                            BuildingId = 1,
                            Level = "First floor"
                        });
                });

            modelBuilder.Entity("Hospital.GraphicalEditor.Model.FloorLabel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("FloorLabels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            FloorId = 1,
                            Text = "ENTRANCE",
                            X = 50,
                            Y = 80
                        });
                });

            modelBuilder.Entity("Hospital.GraphicalEditor.Model.MapPosition", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("MapPositions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Height = 180,
                            Width = 520,
                            X = 30,
                            Y = 20
                        },
                        new
                        {
                            id = 2,
                            Height = 180,
                            Width = 520,
                            X = 30,
                            Y = 460
                        });
                });

            modelBuilder.Entity("Hospital.GraphicalEditor.Model.OutsideDoor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsVertical")
                        .HasColumnType("boolean");

                    b.Property<int>("MapPositionId")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("OutsideDoors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            IsVertical = true,
                            MapPositionId = 1,
                            X = 545,
                            Y = 80
                        },
                        new
                        {
                            id = 2,
                            IsVertical = false,
                            MapPositionId = 1,
                            X = 260,
                            Y = 195
                        },
                        new
                        {
                            id = 3,
                            IsVertical = true,
                            MapPositionId = 2,
                            X = 545,
                            Y = 505
                        },
                        new
                        {
                            id = 4,
                            IsVertical = false,
                            MapPositionId = 2,
                            X = 260,
                            Y = 455
                        });
                });

            modelBuilder.Entity("Hospital.GraphicalEditor.Model.Parking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("Hospital.MedicalRecords.Model.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<bool>("isAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("isPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("isPublishable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Hospital.MedicalRecords.Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activated")
                        .HasColumnType("boolean");

                    b.Property<string>("BloodType")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DoctorName")
                        .HasColumnType("text");

                    b.Property<string>("EMail")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Residence")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Hospital.RoomsAndEquipment.Model.Equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<bool>("InTransport")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransportEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TransportStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("AllEquipment");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Amount = 15,
                            InTransport = false,
                            Name = "Bandage",
                            RoomId = 15,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            id = 2,
                            Amount = 3,
                            InTransport = false,
                            Name = "Operating table",
                            RoomId = 23,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            id = 3,
                            Amount = 11,
                            InTransport = false,
                            Name = "Infusion",
                            RoomId = 1,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            id = 4,
                            Amount = 17,
                            InTransport = false,
                            Name = "Bandage",
                            RoomId = 2,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            id = 5,
                            Amount = 2,
                            InTransport = false,
                            Name = "Operating table",
                            RoomId = 2,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            id = 6,
                            Amount = 23,
                            InTransport = false,
                            Name = "Infusion",
                            RoomId = 23,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            id = 7,
                            Amount = 15,
                            InTransport = false,
                            Name = "Bandage",
                            RoomId = 3,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            id = 8,
                            Amount = 1,
                            InTransport = false,
                            Name = "Operating table",
                            RoomId = 3,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            id = 9,
                            Amount = 11,
                            InTransport = false,
                            Name = "Syringe",
                            RoomId = 3,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            id = 10,
                            Amount = 7,
                            InTransport = false,
                            Name = "Bed",
                            RoomId = 4,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            id = 11,
                            Amount = 4,
                            InTransport = false,
                            Name = "Chair",
                            RoomId = 16,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            id = 12,
                            Amount = 11,
                            InTransport = false,
                            Name = "Bed",
                            RoomId = 5,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            id = 13,
                            Amount = 6,
                            InTransport = false,
                            Name = "Chair",
                            RoomId = 17,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            id = 14,
                            Amount = 25,
                            InTransport = false,
                            Name = "Bandage",
                            RoomId = 5,
                            TransportEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransportStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        });
                });

            modelBuilder.Entity("Hospital.RoomsAndEquipment.Model.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Css")
                        .HasColumnType("text");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("DoorExist")
                        .HasColumnType("boolean");

                    b.Property<int>("DoorX")
                        .HasColumnType("integer");

                    b.Property<int>("DoorY")
                        .HasColumnType("integer");

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<bool>("Vertical")
                        .HasColumnType("boolean");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 148,
                            DoorY = 285,
                            FloorId = 1,
                            Height = 190,
                            Name = "OPERATING ROOM 1",
                            Purpose = "",
                            Vertical = true,
                            Width = 150,
                            X = 0,
                            Y = 150
                        },
                        new
                        {
                            id = 2,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 220,
                            DoorY = 248,
                            FloorId = 1,
                            Height = 100,
                            Name = "OPERATING ROOM 2",
                            Purpose = "",
                            Vertical = false,
                            Width = 150,
                            X = 160,
                            Y = 150
                        },
                        new
                        {
                            id = 3,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 370,
                            DoorY = 248,
                            FloorId = 1,
                            Height = 100,
                            Name = "OPERATING ROOM 3",
                            Purpose = "",
                            Vertical = false,
                            Width = 150,
                            X = 320,
                            Y = 150
                        },
                        new
                        {
                            id = 4,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 680,
                            DoorY = 248,
                            FloorId = 1,
                            Height = 100,
                            Name = "ROOM 1",
                            Purpose = "",
                            Vertical = false,
                            Width = 170,
                            X = 480,
                            Y = 150
                        },
                        new
                        {
                            id = 5,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 680,
                            DoorY = 248,
                            FloorId = 1,
                            Height = 100,
                            Name = "ROOM 2",
                            Purpose = "",
                            Vertical = false,
                            Width = 180,
                            X = 660,
                            Y = 150
                        },
                        new
                        {
                            id = 6,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 728,
                            DoorY = 290,
                            FloorId = 1,
                            Height = 100,
                            Name = "OFFICE 1",
                            Purpose = "",
                            Vertical = true,
                            Width = 110,
                            X = 730,
                            Y = 260
                        },
                        new
                        {
                            id = 7,
                            Css = "staircase",
                            DoctorId = -1,
                            DoorExist = false,
                            DoorX = 728,
                            DoorY = 290,
                            FloorId = 1,
                            Height = 90,
                            Name = "LIFT",
                            Purpose = "",
                            Vertical = false,
                            Width = 150,
                            X = 690,
                            Y = 370
                        },
                        new
                        {
                            id = 8,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 728,
                            DoorY = 485,
                            FloorId = 1,
                            Height = 60,
                            Name = "TOILET",
                            Purpose = "",
                            Vertical = true,
                            Width = 110,
                            X = 730,
                            Y = 470
                        },
                        new
                        {
                            id = 9,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 728,
                            DoorY = 555,
                            FloorId = 1,
                            Height = 60,
                            Name = "TOILET",
                            Purpose = "",
                            Vertical = true,
                            Width = 110,
                            X = 730,
                            Y = 540
                        },
                        new
                        {
                            id = 10,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 148,
                            DoorY = 419,
                            FloorId = 1,
                            Height = 190,
                            Name = "OPERATING ROOM 4",
                            Purpose = "",
                            Vertical = true,
                            Width = 150,
                            X = 0,
                            Y = 410
                        },
                        new
                        {
                            id = 11,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 200,
                            DoorY = 498,
                            FloorId = 1,
                            Height = 100,
                            Name = "ROOM 3",
                            Purpose = "",
                            Vertical = false,
                            Width = 100,
                            X = 160,
                            Y = 500
                        },
                        new
                        {
                            id = 12,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 315,
                            DoorY = 498,
                            FloorId = 1,
                            Height = 100,
                            Name = "ROOM 4",
                            Purpose = "",
                            Vertical = false,
                            Width = 150,
                            X = 270,
                            Y = 500
                        },
                        new
                        {
                            id = 13,
                            Css = "room room-cadetblue",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 475,
                            DoorY = 498,
                            FloorId = 1,
                            Height = 100,
                            Name = "ROOM 5",
                            Purpose = "",
                            Vertical = false,
                            Width = 150,
                            X = 430,
                            Y = 500
                        },
                        new
                        {
                            id = 14,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 100,
                            DoorY = 248,
                            FloorId = 2,
                            Height = 100,
                            Name = "DOCTOR'S OFFICE 1",
                            Purpose = "",
                            Vertical = false,
                            Width = 150,
                            X = 0,
                            Y = 150
                        },
                        new
                        {
                            id = 15,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 260,
                            DoorY = 248,
                            FloorId = 2,
                            Height = 100,
                            Name = "DOCTOR'S OFFICE 2",
                            Purpose = "",
                            Vertical = false,
                            Width = 150,
                            X = 160,
                            Y = 150
                        },
                        new
                        {
                            id = 16,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 420,
                            DoorY = 248,
                            FloorId = 2,
                            Height = 100,
                            Name = "DOCTOR'S OFFICE 3",
                            Purpose = "",
                            Vertical = false,
                            Width = 150,
                            X = 320,
                            Y = 150
                        },
                        new
                        {
                            id = 17,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 595,
                            DoorY = 248,
                            FloorId = 2,
                            Height = 100,
                            Name = "DOCTOR'S OFFICE 4",
                            Purpose = "",
                            Vertical = false,
                            Width = 170,
                            X = 480,
                            Y = 150
                        },
                        new
                        {
                            id = 18,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 680,
                            DoorY = 248,
                            FloorId = 2,
                            Height = 100,
                            Name = "ROOM 1",
                            Purpose = "",
                            Vertical = false,
                            Width = 180,
                            X = 660,
                            Y = 150
                        },
                        new
                        {
                            id = 19,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = false,
                            DoorX = 728,
                            DoorY = 290,
                            FloorId = 2,
                            Height = 104,
                            Name = "STAIRS",
                            Purpose = "",
                            Vertical = true,
                            Width = 70,
                            X = 770,
                            Y = 258
                        },
                        new
                        {
                            id = 20,
                            Css = "staircase",
                            DoctorId = -1,
                            DoorExist = false,
                            DoorX = 728,
                            DoorY = 290,
                            FloorId = 2,
                            Height = 90,
                            Name = "LIFT",
                            Purpose = "",
                            Vertical = false,
                            Width = 150,
                            X = 690,
                            Y = 370
                        },
                        new
                        {
                            id = 21,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 728,
                            DoorY = 485,
                            FloorId = 2,
                            Height = 60,
                            Name = "TOILET",
                            Purpose = "",
                            Vertical = true,
                            Width = 110,
                            X = 730,
                            Y = 470
                        },
                        new
                        {
                            id = 22,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 728,
                            DoorY = 555,
                            FloorId = 2,
                            Height = 60,
                            Name = "TOILET",
                            Purpose = "",
                            Vertical = true,
                            Width = 110,
                            X = 730,
                            Y = 540
                        },
                        new
                        {
                            id = 23,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 148,
                            DoorY = 419,
                            FloorId = 2,
                            Height = 190,
                            Name = "OPERATING ROOM 2",
                            Purpose = "",
                            Vertical = true,
                            Width = 150,
                            X = 0,
                            Y = 410
                        },
                        new
                        {
                            id = 24,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 200,
                            DoorY = 498,
                            FloorId = 2,
                            Height = 100,
                            Name = "ROOM 2",
                            Purpose = "",
                            Vertical = false,
                            Width = 100,
                            X = 160,
                            Y = 500
                        },
                        new
                        {
                            id = 25,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 350,
                            DoorY = 498,
                            FloorId = 2,
                            Height = 100,
                            Name = "OPERATING ROOM 3",
                            Purpose = "",
                            Vertical = false,
                            Width = 300,
                            X = 270,
                            Y = 500
                        },
                        new
                        {
                            id = 26,
                            Css = "room",
                            DoctorId = -1,
                            DoorExist = true,
                            DoorX = 400,
                            DoorY = 398,
                            FloorId = 2,
                            Height = 100,
                            Name = "OPERATING ROOM 1",
                            Purpose = "",
                            Vertical = false,
                            Width = 580,
                            X = 0,
                            Y = 300
                        });
                });

            modelBuilder.Entity("Hospital.GraphicalEditor.Model.Building", b =>
                {
                    b.HasOne("Hospital.GraphicalEditor.Model.Area", "Area")
                        .WithMany()
                        .HasForeignKey("Areaid");

                    b.Navigation("Area");
                });
#pragma warning restore 612, 618
        }
    }
}
