-- Table: public.Credentials

-- DROP TABLE public."Credentials";

CREATE TABLE IF NOT EXISTS public."Credentials"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "PharmacyName" text COLLATE pg_catalog."default",
    "PharmacyLocalhost" text COLLATE pg_catalog."default",
    "ApiKey" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Credentials" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Credentials"
    OWNER to postgres;

DELETE FROM public."Credentials";

INSERT INTO public."Credentials"(
	"Id", "PharmacyName", "PharmacyLocalhost", "ApiKey")
	VALUES (1,'Jankovic','http://localhost:34616/','KQuO1kJn189mfY30X6M1pony4sBOLPbhs0DQLt7NMeo=');
