\connect PharmacyDatabaseDocker

CREATE TABLE IF NOT EXISTS public."Medicines"
(
    "MedicineId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "MedicineName" text COLLATE pg_catalog."default",
    "Manufacturer" text COLLATE pg_catalog."default",
    "SideEffects" text COLLATE pg_catalog."default",
    "Usage" text COLLATE pg_catalog."default",
    "Weigth" double precision NOT NULL,
    "MainPrecautions" text COLLATE pg_catalog."default",
    "PotentialDangers" text COLLATE pg_catalog."default",
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_Medicines" PRIMARY KEY ("MedicineId")
)

TABLESPACE pg_default;

ALTER TABLE public."Medicines"
    OWNER to tester;

INSERT INTO public."Medicines"(
	"MedicineId", "MedicineName", "Manufacturer", "SideEffects", "Usage", "Weigth", "MainPrecautions", "PotentialDangers", "Quantity")
	VALUES (1, 'Brufen', 'Galenika', 'bla', 'blabla', 200.00, 'sjadkn', 'blablabla', 100);
INSERT INTO public."Medicines"(
	"MedicineId", "MedicineName", "Manufacturer", "SideEffects", "Usage", "Weigth", "MainPrecautions", "PotentialDangers", "Quantity")
	VALUES (2, 'Panadol', 'Galenika', 'bla', 'blabla', 500.00, 'ajsndk', 'blablabla', 100);