\connect MyWebApi.Dev
 
-- Table: public.Feedbacks

-- DROP TABLE public."Feedbacks";

CREATE TABLE IF NOT EXISTS public."Feedbacks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Content" text COLLATE pg_catalog."default",
    "IsPublic" boolean NOT NULL,
    "IsPublishable" boolean NOT NULL,
    "IsAnonymous" boolean NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "UserName" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Feedbacks"
    OWNER to admin;

INSERT INTO public."Feedbacks"(
	"Id", "Content", "IsPublic", "IsPublishable", "IsAnonymous", "Date", "UserName")
	VALUES (1, 'Feedback 1', true, true, false, '2021-12-06 20:27:28.916', 'Default User');

INSERT INTO public."Feedbacks"(
	"Id", "Content", "IsPublic", "IsPublishable", "IsAnonymous", "Date", "UserName")
	VALUES (2, 'Feeback 2', false, true, true, '2021-12-06 20:27:28.916', 'Default User');


-- Table: public.Questions-- DROP TABLE public."Questions";CREATE TABLE IF NOT EXISTS public."Questions"(    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),    "Answer" integer NOT NULL,    "IdSurvey" integer NOT NULL,    "Question" text COLLATE pg_catalog."default",    "Section" integer NOT NULL,    CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"))TABLESPACE pg_default;ALTER TABLE public."Questions"    OWNER to admin;


INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'Has doctor been polite to you?', 1);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How would you rate the professionalism of doctor?', 1);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How clearly did the doctor explain you your condition?', 1);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How would you rate the doctors patience with you?', 1);

INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'What is your overall satisfaction with doctor?', 1);

			
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How easy is to use our application?', 0);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How easy it was to schedule an appointment?', 0);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'What is an opportunity to recommend us to your friends and family?', 0);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How satisfied are you with the services that the hospital provides you?', 0);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'What is your overall satisfaction with our hospital?', 0);

INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How would you rate the professionalism of our staff?', 2);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How would you rate the kindness of our staff?', 2);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How clearly did the staff explain you some procedures of our hospital?', 2);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'How yould you rate to what extent staff was available to you during your visit to the hospital?', 2);
	
INSERT INTO public."Questions"(
	"Answer", "IdSurvey", "Question", "Section")
	VALUES (0, 1, 'What is your overall satisfaction with our staff?', 2);
