name: Build and Test Pharmacy App With Every Push to Develop and Master

on:
  push:
  pull_request:

env:
 PHARMACY-PROJECT-SOLUTION : 'PharmacyApplication/PharmacyApplication.sln'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build ${{ env.PHARMACY-PROJECT-SOLUTION }} --configuration Release
    # - name: Test
    #   run: dotnet test ${{ env.PHARMACY-PROJECT-SOLUTION }} --configuration Release --no-build