name: Build Pharmacy App 

on:
  push:
  pull_request:

env:
 PHARMACY-PROJECT-SOLUTION : 'PharmacyApplication/PharmacyApplication.sln'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build ${{ env.PHARMACY-PROJECT-SOLUTION }} --configuration Release
  