name: Deploy

on:
  workflow_dispatch:
  push:
    branches: 
      # - 'master'
      - 'develop'
      - 'fix/deploy-script'
      - 'fix/e2e-tests'
 
jobs:
  deploy:
    runs-on : ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: appleboy/ssh-action@master
        with:
          host: 79.101.34.218 
          username: 'student'
          key: ${{ secrets.SSH_KEY }}
          port: 22202
          script: |
            cd psw-firma1
            git checkout feat/docker-secrets
            git pull origin feat/docker-secrets
            docker system prune -f
            docker swarm leave --force
            docker swarm init
            printf  ${{ secrets.HOSPITAL_USER_PASS }} | docker secret create db_user_hospital -
            printf ${{ secrets.HOSPITAL_PASS }} | docker secret create db_pass_hospital -
            cd WebAppCore/
            cd stacks-hospital/
            docker stack deploy --compose-file=docker-compose.yml hosp_secret
            

            
           