name: Deploy

on:
  workflow_dispatch:
  push:
    branches: 
      # - 'master'
      - 'develop'
      - 'feat/deploy-script'

jobs:
  deploy:
    runs-on : ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: appleboy/ssh-action@master
      #   uses: shimataro/ssh-key-action@v2
      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        with:
          # host: ${{ secrets.SSH_HOST }} 
          host: 79.101.34.218 
          username: 'student'
          key: ${{ secrets.SSH_KEY }}
          port: 22202
          script: |
            cd psw-firma1
            git checkout develop
            git pull origin develop
            cd PharmacyApplication/
            docker-compose build --no-cache
            docker-compose up -d
            cd ..
            cd WebAppCore/
            cd stacks-hospital/
            docker-compose build --no-cache
            docker-compose up -d
            logout
            ssh -L 4202:localhost:4202 -L 8081:localhost:8081 -L 3000:localhost:3000 -L 8080:localhost:8080 -p 22202 student@79.101.34.218
