name: e2e-testing
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute e2e tests 
        run: docker-compose -f docker-compose-e2e.yml up --exit-code-from e2e-testing-hospital e2e-testing-hospital


