name: Packaging Hospital Library

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

env:
 PROJECT-DLL : 'WebAppCore/Hospital/Hospital.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build ${{ env.PROJECT-DLL }} --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test ${{ env.PROJECT-DLL }} --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack ${{ env.PROJECT-DLL }} --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push NuGet.HospitalLibrary.${VERSION}.nupkg --source https://nuget.pkg.github.com/World-Vision-Clinic/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}  