name: unit-testing
on:
  push:
  pull_request:


jobs:
  Run-Unit-Tests:

    runs-on: ubuntu-latest
    env:
      PHARMACY_PROJECT_SOLUTION: PharmacyApplication
      HOSPITAL_PROJECT_SOLUTION: WebAppCore/HospitalTests/HospitalTests.csproj
      INTEGRATION_PROJECT_SOLUTION: WebAppCore/IntegrationTests/IntegrationTests.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies pharmacy
        run: dotnet restore ${PHARMACY_PROJECT_SOLUTION}
      - name: Build pharmacy
        run: dotnet build ${PHARMACY_PROJECT_SOLUTION} --configuration Release --no-restore
      - name: Test pharmacy
        run: dotnet test ${PHARMACY_PROJECT_SOLUTION} --no-restore --verbosity quiet --filter FullyQualifiedName~UnitTests


      - name: Install dependencies hospital
        run: dotnet restore ${HOSPITAL_PROJECT_SOLUTION}
      - name: Build hospital
        run: dotnet build ${HOSPITAL_PROJECT_SOLUTION} --configuration Release --no-restore
      - name: Test hospital
        run: dotnet test ${HOSPITAL_PROJECT_SOLUTION} --no-restore --verbosity quiet --filter FullyQualifiedName~UnitTests


      - name: Install dependencies integration
        run: dotnet restore ${INTEGRATION_PROJECT_SOLUTION}
      - name: Build integration
        run: dotnet build ${INTEGRATION_PROJECT_SOLUTION} --configuration Release --no-restore
      # - name: Test integration
      #   run: dotnet test ${INTEGRATION_PROJECT_SOLUTION} --no-restore --verbosity quiet --filter FullyQualifiedName!~IntegrationTests
