version: '3.2' 

services:
  hospital-front:
    image: jelenahrnjak/hospital-front:latest
    depends_on:
      - "hospital-api"
    # build:
    #   context: ../../patient-portal-front/
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks: 
      - application

  hospital-api:
    image: jelenahrnjak/hospital-api:latest
    depends_on:
      - "database"
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8080:1025"     
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: MyWebApi.Dev
      DATABASE_USER: admin
      DATABASE_PASSWORD: ftn
    networks:
      - application
  
  database: 
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - type: volume
        source: db_volume
        target: /var/lib/postgresql/data
      - type: bind
        source: ./dbscripts/seed.sql 
        target: /docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "ftn"
      POSTGRES_DB: "MyWebApi.Dev"
    networks:
      - application
volumes:
  db_volume:
    #name: database

networks:
  application:
    #name: application
    driver: bridge