version: '3.2' 

secrets:
  db_pass_hospital:
    external: true
  db_user_hospital:
    external: true

services:
  hospital-front:
    image: darkelfff/hospital-front-s:latest
    #image: hospital-front
    depends_on:
      - "hospital-api"
    build:
      context: ../../patient-portal-front/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks: 
      - application

  hospital-api:
    image: darkelfff/hospital-api:latest
    depends_on:
      - "database"
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8080:8080"     
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: MyWebApi.Dev
      DATABASE_USER_FILE: /run/secrets/db_user_hospital
      DATABASE_PASSWORD_FILE: /run/secrets/db_pass_hospital
    networks:
      - application
    secrets:
      - source: db_pass_hospital
        uid: '5000'
        gid: '5000'
        mode: 0440
      - db_user_hospital 
  
  database: 
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - type: volume
        source: db_volume
        target: /var/lib/postgresql/data
      - type: bind
        source: ./dbscripts/seed.sql 
        target: /docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user_hospital
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass_hospital
      POSTGRES_DB: MyWebApi.Dev
    networks:
      - application
    secrets:
     - db_pass_hospital
     - db_user_hospital 
volumes:
  db_volume:
    #name: database

networks:
  application:
    #name: application
    driver: overlay
